name: carapacik_lints
description: The most necessary lints for Flutter to encourage good coding practices
version: 1.8.0
repository: https://github.com/Carapacik/carapacik_lints
topics:
  - analysis
  - lint
  - lints
  - linter
environment:
  sdk: ^3.4.0
