name: carapacik_lints
description: The most necessary lints for Flutter to encourage good coding practices.
version: 1.3.0
repository: 'https://github.com/Carapacik/carapacik_lints'
environment:
  sdk: '>=2.19.0 <4.0.0'
